### PR TITLE
Translate README.md

### PR DESCRIPTION
**Pull request by felixvd**
In all seriousness, you should send this to the ROBOMECH organizers, because platex is a plague upon this earth and no one should have to compile papers on their desktop PCs in this day and age.

### CODE REVIEW

**Comment by lotfielhafi** [comment]
Actually, I did:

> Dear Lotfi EL HAFI,
> 
> Hi, I am Masashi Konyo, the Program Chair of ROBOMECH2017.
> Thank you for letting us know the current problem and your kind suggestion.
> We will consider a modification based on your suggestion and replace
> the template if necessary.
> 
> Thank you so much for your great support for the conference.
> 
> Best regards,
> 
> M. Konyo
> Program Chair of ROBOMECH2017

**Comment by felixvd** [comment]
Good job. Great response. Don't forget to accept or decline this pull request btw.

**Comment by lotfielhafi** [comment]
Yes, but first I would like to understand the differences between the 3 merge options I have in GitHub. I'll do it later.

**Comment by lotfielhafi** [comment]
Sorry for the delay. I merged your changes and will soon open the repo.

**Pull request merged**
